### ISSUE TITLE
When several jogAxis requests are made, ESP8266 overflows and restarts.

### ISSUE THREAD

**Issue by gvJaime** [malariaspot/MicroSpot-WiFi#13]
It has been confirmed that the whole system restarts, by putting a homeAxis() command in the Mechanical Toggle routine.

This is a very important issue because jogging is used for panning: one of the most common user operations.

**Comment by alexx666** [comment]
As we already saw its a memory problem, which is currently partly solved. 
Pending: String parsing and stress tests

**Comment by gvJaime** [comment]
torture.py tests reveal that, if the request spamming has a period < 1second, the ESP8266 overflows after ~195 requests.

It doens't restart with the python script, but it restarts with a phone.

The python script failure is limited to just the esp8266 returning empty responses, although commands can be sent. After a while it sends the right responses again.

**Comment by alexx666** [comment]
Another simple test we could run is try to overflow the esp8266 by fluding it with /ayy/lmao requests. Test it with deferent speeds. Each second, each 500ms, 250ms, 100ms etc...

That would help us narrow down the memory bottle neck. If it fails in any way, it would mean that either we dont manage memory correctly in MicroServer or WiFiServer simply has limitations to how many requests it can handle.

On the other hand if it doesnt restart or fail that means Mechanical.ccp has the memory problem, because all other requests, appart from /ayy/lmao, require it to be called.

**Comment by gvJaime** [comment]
**IMPORTANT:** Adding a ```delete client``` after ```client->stop()``` breaks the OTAs.

It also difficults the upload by serial, because the esp8266 softlocks with the serial enabled, so the ESPRecovery sketch cannot be loaded into the ATMega

**Comment by gvJaime** [comment]
Won't fix
